targets:
  - name: backend-repo
    lane: backend
    repo: /tmp/rv-target-origins/backend-repo
    sha: 60fe26124c7357c4745f0ecd333cc24506008488
    snapshot_path: /tmp/targets/backend-repo
  - name: ui-repo
    lane: ui
    repo: /tmp/rv-target-origins/ui-repo
    sha: dfebfbde86d2eadcd7a5ca94c685ea4451174514
    snapshot_path: /tmp/targets/ui-repo
